component_depth: 1

exclude:
  - /src/sources/forus-webshop/js/angular-1/components/.*
  - /src/sources/forus-platform/js/angular-1/components/.*
  - /src/sources/forus-webshop/js/angular-1/controllers/.*
  - /src/sources/forus-platform/js/angular-1/controllers/.*
  - /src/sources/forus-backend/js/angular-js/providers/ApiRequestProvider.js
  - /src/sources/forus-webshop/js/angular-1/directives/PincodeControlDirective.js
  - /src/sources/forus-platform/js/angular-1/routers/router.js
  - /src/sources/forus-platform/js/angular-1/libs/AwesomeQrCode.js
  - /src/sources/forus-platform/js/angular-1/services/GoogleMapService.js
  - /src/gulpfile.js
  - /src/qdt-env.sample.js
  - /src/qdt-config.js
