component_depth: 1

exclude:
  - /src/lib/.*
  - /src/sources/forus-platform/js/angular-1/i18n/.*
  - /src/qdt-env.sample.js
  - /src/qdt-config.js
  - /src/sources/forus-platform/js/angular-1/libs/AwesomeQrCode.js
  - /src/sources/forus-platform/js/angular-1/routers/router.js
  - /src/sources/forus-webshop/js/angular-1/routers/router.js

