name: Build Frontend

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Compile frontends
      uses: actions/setup-node@v1
      with:
        node-version: 10.16    
    - name: Install gulp
      run: npm install gulp
    - name: Install dependencies
      run: cd src && npm install
    - name: Init
      run: cd src && gulp init
    - name: Build
      run: cd src && gulp compile
